// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WikiFloraAPI.Data;

#nullable disable

namespace WikiFloraAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230730075241_FloraAndFloraDataRalation")]
    partial class FloraAndFloraDataRalation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("WikiFloraAPI.Models.Flora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BanglaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contributer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OthersName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Floras");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.FloraPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CoverPhotoUrlId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FloraId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoverPhotoUrlId");

                    b.HasIndex("FloraId")
                        .IsUnique();

                    b.ToTable("FloraPhoto");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.Hierarchy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BionomialName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FloraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kingdom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FloraId")
                        .IsUnique();

                    b.ToTable("Hierarchy");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Credit")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FloraId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FloraPhotoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FloraId");

                    b.HasIndex("FloraPhotoId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.ScientificName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FloraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificEpithet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FloraId")
                        .IsUnique();

                    b.ToTable("ScientificName");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.FloraPhoto", b =>
                {
                    b.HasOne("WikiFloraAPI.Models.Photo", "CoverPhotoUrl")
                        .WithMany()
                        .HasForeignKey("CoverPhotoUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiFloraAPI.Models.Flora", null)
                        .WithOne("FloraPhoto")
                        .HasForeignKey("WikiFloraAPI.Models.FloraPhoto", "FloraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoverPhotoUrl");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.Hierarchy", b =>
                {
                    b.HasOne("WikiFloraAPI.Models.Flora", "Flora")
                        .WithOne("Hierarchy")
                        .HasForeignKey("WikiFloraAPI.Models.Hierarchy", "FloraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flora");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.Photo", b =>
                {
                    b.HasOne("WikiFloraAPI.Models.Flora", "Flora")
                        .WithMany()
                        .HasForeignKey("FloraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WikiFloraAPI.Models.FloraPhoto", null)
                        .WithMany("PhotoUrls")
                        .HasForeignKey("FloraPhotoId");

                    b.Navigation("Flora");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.ScientificName", b =>
                {
                    b.HasOne("WikiFloraAPI.Models.Flora", "Flora")
                        .WithOne("ScientificName")
                        .HasForeignKey("WikiFloraAPI.Models.ScientificName", "FloraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flora");
                });

            modelBuilder.Entity("WikiFloraAPI.Models.Flora", b =>
                {
                    b.Navigation("FloraPhoto")
                        .IsRequired();

                    b.Navigation("Hierarchy")
                        .IsRequired();

                    b.Navigation("ScientificName")
                        .IsRequired();
                });

            modelBuilder.Entity("WikiFloraAPI.Models.FloraPhoto", b =>
                {
                    b.Navigation("PhotoUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
